= Project 1 
:toc: left


== Objectifs du projet

On va développer une application web qui permet à des utilisateurs de poster des messages et voir les messages des autres utilisateurs.
Ils doivent se créer un compte et s'authentifier avant de pouvoir poster un message.

Il y aura un compte administrateur qui peut lister les utilisateurs inscrits et supprimer les messages qu'il souhaite.

On va construire le projet petit à petit.

== Architecture d'une application web

Quand on parle d'une application web, on parle souvent de client et de serveur.
Le client est dans ce cas le navigateur qui va communiquer avec un serveur, dans notre cas un serveur HTTP.

A chaque action de l'utilisateur (ouverture de la page, clic sur un lien ou bouton, ...), le navigateur va envoyer une requête HTTP au serveur, et va afficher le résultat de la réponse à l'utilisateur. 

Au début des sites web, chaque clic ou action chargeait une nouvelle page. On parle parfois de "Multi Page Applications". 
Avec le temps, les développeurs voulaient quelque chose de plus dynamique car souvent, on a pas besoin de recharger toute la page après chaque action. On a alors inventé "Ajax".
Plus récemment, on parle de Single Page Application, avec des frameworks comme React, Vue.js ou d'autres.
Beaucoup de sites aujourd'hui sont des SPA, mais il y a encore des MPA quand on a pas besoin du côté dynamique.

Dans notre cas, on va rester sur une application web classique en multi-page. 
Pas la peine de complexifier les choses dans un premier temps. On pourra ensuite faire un SPA si tu veux.


=== Introduction à HTTP

Comme je disais, le navigateur va envoyer une requête HTTP au serveur pour chaque action de l'utilisateur.
Je ne vais pas rentrer dans les détails du protocole HTTP, car c'est très complexe et vaste.

Je ne sais pas si tu as eu des cours de réseaux ou pas, mais si tu ne vois pas trop ce qu'est http, tu peux déjà regarder ici : https://www.commentcamarche.net/contents/520-le-protocole-http

On pourra en discuter plus en détail si tu veux.

=== Choix du serveur http

Il y a pas mal de choix en Python pour créer un serveur http, mais les plus connus sont Flask et Django.

Flask est plus bas-niveau et propose moins de fonctionnalités, mais il est plus facile à prendre en main.
Django est plus complet, mais on risque de passer plus de temps à comprendre comment Django fonctionne, plutôt que se focaliser sur notre code.

On va utiliser Flask.


== Exercices 

=== Exercice 1 

Objectif : s'assurer que ton pc est bien configuré pour lancer le serveur.

Aller dans le répertoire python-flask et explorer le contenu.
C'est un projet minimal qui utilise Flask.

Il faut donc installer Flask sur ton pc avant de pouvoir exécuter le code.
Voir ce lien (https://flask.palletsprojects.com/en/1.1.x/installation/) pour plus d'infos.

Une fois Flask installé, tu peux lancer le serveur avec : 

[source,bash]
----
flask run
----

Si tout se passe bien, tu devrais voir une très belle page sur http://127.0.0.1:5000/ 


=== Exercice 2

Objectif : Enregistrer les messages en base de données

Actuellement, le code affiche le contenu du champ message dans la console, mais ne persiste rien du tout en base de données.

La première étape va être de reprendre le code que tu as fais pour te connecter à MySQL, l'ajouter à ce projet dans une fonction séparée, ou mieux, dans un autre fichier (c'est une bonne pratique de séparer ton code).

Il faudra créer une table en BDD pour les messages. Je pense que c'est intéressant d'avoir deux colonnes : une pour le contenu du message et une autre pour la date à laquelle on a envoyé le message.

Enfin, il faut enregistrer le nouveau message en BDD en complétant la fonction add_message. 


=== Exercice 3 

Objectif : Lister les messages

Cette fois, on va tout simplement lister les messages en base de données.

Il faut d'un côté récupérer les messages de Mysql et ensuite les afficher.

On peut afficher les messages dans la page d'accueil, en dessous du formulaire d'ajout de message.

Je te laisse regarder la page sur les templates Flask : https://flask.palletsprojects.com/en/1.1.x/quickstart/#rendering-templates

Il faudra que tu regardes comment passer les messages du code python au template, et comment les afficher dans la page html. 
Pas besoin de faire un truc compliqué, un simple listing suffit.


=== Exercice 4

Objectif : Ajouter la création de compte

On s'attaque aux choses sérieuses. 
Pour l'instant, nos messages sont anonymes et n'importe qui peut écrire.
On va donc implémenter la gestion des utilisateurs.

On va d'abord créer une nouvelle page accessible à l'adresse http://localhost:5000/signup par exemple.
Sur cette page, il y a tout simplement un formulaire avec quelques champs (nom d'utilisateur, mot de passe, email, ... )

Quand on valide le formulaire, le serveur reçoit une requête et va ajouter le nouvel utilisateur.

Il faut évidemment créer la table etc.. Mais surtout, réfléchir à comment stocker le mot de passe.
Je te laisse regarder ce lien : https://pboyd.io/posts/how-not-to-store-passwords/

Il faudra également ajouter un identifiant à l'utilisateur. A toi de voir si tu veux utiliser un id auto-incrémenté, ou bien un uuid.

Question(s) : 

* Pourquoi on utilise un id? Quel est l'intérêt?


=== Exercice 5

Objectif : Ajouter l'authentification

C'est très bien, on peut se créer un compte... Mais je peux pas l'utiliser!

La prochaine étape est donc de créer une page de connexion avec un formulaire basique, et le serveur va vérifier que l'utilisateur existe et que le mot de passe est bon.

Tu vas pouvoir t'inspirer de tout ce que tu as fait jusqu'à présent.

Mais il y a un problème, comment stocker le fait que l'utilisateur s'est connecté?
On va utiliser le concept de "sessions".

Pour chaque requête http, tu as un objet "request" et un objet "response", mais également un objet "session" qui va te permettre de stocker des données qui ne seront pas perdues entre chaque requête.

[source,python]
----
from flask import abort, session, redirect, url_for, render_template

app = Flask(__name__)
app.secret_key = b'_5#ax2L"FaQ4z\n\xec]/'

@app.route('/xxx', methods=['POST'])
def xxx():

    if 'username' in session:
        print(session['username'])        

    session['username'] = "john"

    return redirect(url_for('home'))
----

Donc, si l'utilisateur s'authentifie avec succès, tu vas pouvoir ajouter dans la session tout ce que tu veux (username, ...).

Pour activer les sessions, il ne faut pas oublier l'import et l'ajout d'une clé secrète.
 

=== Exercice 6

Objectif : Modifier le stockage du message pour ajouter les infos sur l'utilisateur

On sait maintenant à tout moment quel utilisateur est connecté.

On peut donc modifier le code pour lier l'utilisateur à chaque message posté, et on va aussi modifier la liste des messages affichés dans home pour indiquer qui a écrit le message.

A ton avis, quel concept on utilise pour faire ce lien?


=== Exercice 7

Objectif : Ajouter un compte admin

XXX


=== Exercice 8

Objectif : Donner la possibilité à l'admin de supprimer un message

XXX


=== Exercice 9

Objectif : Créer une nouvelle page pour lister les utilisateurs inscrits

XXX


=== Exercice 10

Objectif : Protéger les pages 

XXX

=== Exercice 11

Objectif : Ajouter des tests unitaires

XXX

=== Exercice 12

Objectif : Déployer l'application sur internet

XXX

=== Exercice 13 : Bonus

* Comptes doublons
* sql injection