DROP TABLE MESSAGES;

DROP TABLE USERS;

CREATE TABLE USERS(ID INT PRIMARY KEY NOT NULL, NAME TEXT);

CREATE TABLE MESSAGES(
  ID INT PRIMARY KEY NOT NULL,
  CONTENT TEXT,
  USER_ID INT,
  FOREIGN KEY(USER_ID) REFERENCES USERS(ID)
);